apiVersion: v1
kind: ConfigMap
metadata:
 name: hc-nodepool-vmdratio
 namespace: clusters
data:
 tuning: |
   apiVersion: tuned.openshift.io/v1
   kind: Tuned
   metadata:
     name: hc-nodepool-vmdratio
     namespace: openshift-cluster-node-tuning-operator
   spec:
     profile:
     - data: |
         [main]
         summary=Custom OpenShift profile
         include=openshift-node
 
         [sysctl]
         vm.dirty_ratio="55"
       name: hc-nodepool-vmdratio
     recommend:
     - priority: 20
       profile: hc-nodepool-vmdratio
